docs: add in-code samples for noncurrent time OLM rules
googleapis/nodejs-storage pull request #1216
Opened 2020-06-11 22:53 UTC by jkwlui

Not expecting any code changes to support these new fields, since `LifecycleRule.conditions` is typed as `condition: {[key: string]: boolean | Date | number | string}`.

Closes #1197

2020-06-11 23:05 UTC, JustinBeckwith approved these changes

2020-06-12 02:34 UTC, laljikanjareeya requested changes
It's good to have unit test and system test for same.

2020-06-19 02:37 UTC, laljikanjareeya approved these changes

2020-06-19 20:40 UTC, jkwlui commented
Block until feature is available publicly.

2020-07-07 21:55 UTC, jkwlui commented
Added documentation on daysSinceCustomTime and customTimeBefore fields.

2020-08-24 21:11 UTC, merged