docs(samples): add/remove bucket labels sample
googleapis/nodejs-storage pull request #1270
Opened 2020-08-18 10:35 UTC by laljikanjareeya

PR contains below samples:

- Add bucket labels(storage_add_bucket_label)
- Remove bucket labels(storage_remove_bucket_label)

2020-08-27 13:41 UTC, AVaksman requested changes

2020-08-27 13:41 UTC, AVaksman commented on samples/removeBucketLabel.js
> +  // const label= = 'Name of a label, e.g. label';
```suggestion
  // const label = 'Name of a label, e.g. label';
```

2020-08-27 13:41 UTC, AVaksman commented on samples/addBucketLabel.js
> +function main(bucketName = 'my-bucket') {
should we add `label` param here as well?

2020-08-27 13:41 UTC, AVaksman commented on samples/system-test/buckets.test.js
> +  const output = execSync(`node addBucketLabel.js ${bucketName}`);
Should we pass a label here as well?

2020-09-16 16:04 UTC, AVaksman approved these changes

2020-09-17 20:06 UTC, frankyn commented
Hi @laljikanjareeya,

Thanks for sending these PRs. We are pending @JesseLovelace return to review these samples. Please continue sending them and we can wait to merge until they're back to review.

cc: @JustinBeckwith for vis. I'll be adding "Do Not Merge" label until then, but this is prioritized work that you can continue @laljikanjareeya.

Thank you.

2020-11-10 02:38 UTC, laljikanjareeya commented
Gentle ping @JesseLovelace

2020-12-04 07:04 UTC, laljikanjareeya commented
@JesseLovelace Can you take a look into samples PR as this has been since long. Thanks!
cc: @frankyn

2020-12-10 17:29 UTC, frankyn requested changes

2020-12-10 17:29 UTC, frankyn commented on samples/removeBucketLabel.js
> +  // const label= = 'Name of a label, e.g. label';
Double `=`
Does this represent the label_key? Can it be a list of keys?

2020-12-17 21:09 UTC, frankyn approved these changes

2020-12-17 21:34 UTC, merged