docs: Clarify how to specify projectID in samples.
googleapis/nodejs-storage pull request #1400
Opened 2021-02-10 00:40 UTC by tritone

Adds a comment to quickstart sample as well as bucket creation
samples (which send the project ID in the request) to clarify that
Storage can be initialized for a specific project.

Fixes an internal feedback bug on these samples.

2021-02-10 03:40 UTC, JustinBeckwith requested changes
I worry a little here from a consistency standpoint.  We have thousands of samples where we don't specifically show identifying a custom Project Id, why are these particular ones special?

In 99/100 cases, I would expect folks want to use the same project id that either:
- Is specified by `gcloud config set projectId
- Defined by the `GCLOUD_PROJECT` env var
- Obtained from the GCE metadata service

These libraries do that detection automatically, so I want to be *super* careful on how we advise folks here.

2021-02-10 03:40 UTC, JustinBeckwith commented on samples/createBucketWithStorageClassAndLocation.js
> +  // const storage = new Storage({"my-gcp-project"});
We would actually want:
```js
const storage = new Storage({ projectId: 'my-gcp-project' });
```

2021-02-10 05:27 UTC, frankyn requested changes

2021-02-10 05:27 UTC, frankyn commented on samples/createBucketWithStorageClassAndLocation.js
> +  // const storage = new Storage({"my-gcp-project"});
Could you include the path to credentials as well?

2021-03-02 18:04 UTC, shaffeeullah commented
Resolved by https://github.com/googleapis/nodejs-storage/pull/1413

2021-03-02 18:04 UTC, closed without merging